version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./backend/:/go/src/app
    tty: true
    ports:
      - 8080:8080
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend/:/home/node/app
    tty: true
    ports:
      - 5173:5173