version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    volumes:
      - ./backend/:/go/src/app
    tty: true
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Tokyo
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    volumes:
      - ./frontend/:/home/node/app
    tty: true
    ports:
      - 5173:5173
  db:
    container_name: ${DB_HOST}
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-store:/var/lib/postgresql/data
    ports: 
      - ${DB_PORT}:5432

volumes:
  db-store: